<a href="https://colab.research.google.com/github/tasmimjoti/Deep-Learning-with-PyTorch/blob/main/List_to_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [4]:
import torch
a = torch.ones(3)

In [5]:
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [9]:
b = torch.zeros(6)

In [10]:
b[0] = 4.0
b[1] = 1.0
b[2] = 5.0
b[3] = 3.0
b[4] = 2.0
b[5] = 1.0

In [11]:
b =  torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
b

tensor([4., 1., 5., 3., 2., 1.])

In [12]:
float(b[0]), float(b[1])

(4.0, 1.0)

In [13]:
b = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
b

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [14]:
b.shape

torch.Size([3, 2])

In [15]:
b = torch.zeros(3, 2)
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [16]:
b =  torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
b

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [17]:
b[0, 1]

tensor(1.)

In [18]:
b[0]

tensor([4., 1.])

In [19]:
list1 = list(range(6))
list1[:]
list1[1:4]
list1[1:]
list1[:4]
list1[:-1]
list1[1:4:2]

[1, 3]

In [20]:
b[1:]
b[1:, :]
b[1:, 0]
b[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [21]:
b =  torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
b.storage()

<ipython-input-21-51c4daaf4ef4>:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  b.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [22]:
b_storage = b.storage()
b_storage[0]

4.0

In [23]:
b.storage()[1]

1.0

In [24]:
b = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
b_storage = b.storage()
b_storage[0] = 2.0
b

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [25]:
b = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
b2 = b[1]
b2.storage_offset()

2

In [26]:
b2.size()

torch.Size([2])

In [27]:
b2.shape

torch.Size([2])

In [28]:
b.stride()

(2, 1)

In [29]:
b2 = b[1]

In [30]:
b2.size()

torch.Size([2])

In [31]:
b2.storage_offset()

2

In [32]:
b2.stride()

(1,)

In [33]:
b = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
b2 = b[1]
b2[0] = 10.0
b

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [34]:
b = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
b2 = b[1].clone()
b2[0] = 10.0
b

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [35]:
b = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
b

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [36]:
b_t = b.t()
b_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [37]:
id(b.storage()) == id(b_t.storage())

False

In [38]:
b.stride()

(2, 1)

In [39]:
b_t.stride()

(1, 2)